dist: trusty
language: cpp

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - pip install --user cpp-coveralls


before_script:
  - mkdir build
  - cd build
  - cmake .. -DCOVERAGE=1

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - make
  - bin/GambitEngineTest --gtest_filter=*-PerftFixture*

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"