dist: xenial
language: cpp

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - pip install --user cpp-coveralls


before_script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
  - cmake . -DCODE_COVERAGE=1

script:
  - make
  - bin/GambitEngineTest

after_success:
  - coveralls --root . --gcov-options '\-lp' -E ".*include.*" -E ".*googletest.*"